### ISSUE TITLE
バグ

### ISSUE THREAD

**Issue by ken-okabe** [buhoho/fadoshtui#1]
しょうもないバグがいっぱいあるんだが、
デジタルTatooで残すのはここでいいか？

**Comment by buhoho** [comment]
ken-okabe様、

この度は私のリポジトリにコメントをいただき、ありがとうございます。コメントの内容を拝見しましたが、具体的なバグの報告や改善提案が含まれていないようです。プロジェクトの改善に役立てるためにも、発生している問題の詳細をIssueとして登録していただけますと幸いです。

バグの具体的な状況、再現手順、期待される結果等を教えていただければ、それを元に改善に取り組むことが可能です。

何卒、より良いプロジェクト運営のため、ご協力をお願いいたします。

**Comment by ken-okabe** [comment]
いかなる理由をもって君に当方が「プロジェクトの改善に役立てる」ことをしたり、当方に「ご協力をお願い」できると思ったのだろうか？
デジタルTatooを残しただけだよ。
